### PR TITLE
LPS-183021 ftl websphere bug ci test

### PR DESCRIPTION
**Pull request by oliv-yu**
https://github.com/liferay-search/liferay-portal/pull/899

testing out changes via websphere

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:search-environments

**Comment by xbrianlee** [comment]
ci:test:search-environments

The previous build seems to still be running, but just in case it fails, I'm going to kick off another run since this is high priority

**Comment by oliv-yu** [comment]
ci:test:search-environments

**Comment by xbrianlee** [comment]
ci:close

**Pull request closed without merging**
