### PR TITLE
LPS-106850 - As a search developer, I want to use ADTs to customize the Modified Facet Widget

### PR DESCRIPTION
**Pull request by thektan**
http://issues.liferay.com/browse/LPS-106850

I'm getting this strange error when changing display styles. The page renders inside of the configuration modal instead of closing, but the change still saves.

Logs show this https://gist.github.com/thektan/7d1a9952cc94b8e0c3cc1ac503ce5eb5 which seems like the issue is somewhere here

```
at com.liferay.portal.search.web.internal.modified.facet.portlet.action.ModifiedFacetPortletConfigurationAction.processAction(ModifiedFacetPortletConfigurationAction.java:105)
```

But I'm not seeing a reason for it to be breaking there.

Could you try changing the display styles for the modified facet? I want to make sure it isn't a local database issue.

Thanks!

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
I see that error too! I noticed it on Type Facets as well, but it didn't seem like it was related to the changes made from ADTs.

**Comment by oliv-yu** [comment]
Hi, could you also update modified_facet.js and add a few checks for null values? I seem to be getting an `Uncaught TypeError: Cannot read property 'on' of undefined at ModifiedFacetFilter._initializeFormValidator` after making a template with no custom date range.

**Comment by thektan** [comment]
@oliv-yu Added checks so the javascript wouldn't break on undefined values. 👍 Nice catch!

**Comment by thektan** [comment]
Updated using radio buttons instead of checkboxes. Added screenshots in https://issues.liferay.com/browse/LPS-106850

Let me know if you notice anything else! Thanks!

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
Submitted to https://github.com/brianchandotcom/liferay-portal/pull/85351

**Pull request closed without merging**
