### PR TITLE
LPS-104941 portal-search-tuning-rankings-web: Extend timeout

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-104941

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:test

**Comment by joshchong** [comment]
ci:test

**Comment by oliv-yu** [comment]
ci:test

**Comment by oliv-yu** [comment]
ci:test

**Comment by oliv-yu** [comment]
ci:test

**Comment by oliv-yu** [comment]
ci:test

**Comment by oliv-yu** [comment]
ci:test

**Pull request closed without merging**
