### PR TITLE
LPS-98391 - Delta parameter doesn't remove from URL when selecting the default pagination

### PR DESCRIPTION
**Pull request by thektan**
http://issues.liferay.com/browse/LPS-98391

Since the delta parameter is being added in the taglib, I had to make the change directly to it. I also made the same change to the non-lexicon version to keep the experience the same even though it isn't being used in the search results widget.

I don't imagine any issues with removing the default delta from the URL across all places in portal using the `liferay-ui:page-iterator` and `liferay-ui:search-paginator` taglibs, but let me know if you think of anything.

Thanks!

cc @jonmak08

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:forward

**Pull request closed without merging**
