### PR TITLE
 [TS] LPS-102287 Moves js to liferay-search-modified-facet for better maintainability

### PR DESCRIPTION
**Pull request by thektan**
http://issues.liferay.com/browse/LPS-102287

@oliv-yu Let me know if you find this better organized. 🙂 

I tried to keep the js module with a similar structure to not introduce any drastic changes.

cc: @jonmak08

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
Hi Kevin,

Can you pleas add the [TS] designation to the PR subject? Thanks for taking care of the review. :+1:

**Comment by thektan** [comment]
Running tests at: https://github.com/thektan/liferay-portal/pull/65

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by thektan** [comment]
ci:stop

**Comment by oliv-yu** [comment]
👍 https://github.com/brianchandotcom/liferay-portal/pull/78969

**Pull request closed without merging**
