### PR TITLE
LPD-39088 Refactor disk space

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
i didnt test this manually or run it through CI yet, if you could take care of that and just verify i didnt miss anything on the frontend code i would appreciate it! trying to have this merged by thurs. thanks!

**Comment by oliv-yu** [comment]
ci:report:40937324

**Pull request closed without merging**
